# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'     #官方仓库地址
source 'https://github.com/JiWuChao/MyPrivatePodSpec.git' #私有仓库地址

target 'testSNNetwork' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'SNNetwork', '~> 0.0.4'
  # Pods for testSNNetwork

  target 'testSNNetworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testSNNetworkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
