# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testCrossroad' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Crossroad'
pod 'URLNavigator'
  # Pods for testCrossroad

  target 'testCrossroadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testCrossroadUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
