osx_image: xcode10.2
language: objective-c
sudo: required
env:
  global:
    - PROJECT="URLNavigator.xcodeproj"
    - SCHEME="URLNavigator-Package"
    - IOS_SDK="iphonesimulator12.2"
    - TVOS_SDK="appletvsimulator12.2"
    - FRAMEWORK="URLNavigator"
  matrix:
    - SDK="$IOS_SDK"      TEST=1  DESTINATION="platform=iOS Simulator,name=iPhone 7,OS=12.2"
    - SDK="$TVOS_SDK"     TEST=1  DESTINATION="OS=12.2,name=Apple TV 4K"

install:
  - swift --version

before_script:
  - set -o pipefail
  - swift package generate-xcodeproj

script:
  - xcodebuild clean build test
    -project "$PROJECT"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    -enableCodeCoverage YES
    APPLICATION_EXTENSION_API_ONLY=YES
    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash) -X xcodeplist -J 'URLNavigator'
