# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Network' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Network//, '~> 5.0.0-beta.6'
#  pod 'Alamofire', '~> 5.0.0-beta.6'
  pod 'Alamofire','~> 4.8.2'
#  pod 'Restofire', '~> 4.1.0'
  pod 'RxSwift', '~> 5'
  pod 'SwiftyJSON'
  target 'NetworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NetworkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
